import type { Metadata } from "next";
import "./globals.css";

import { Be_Vietnam_Pro, Poppins } from "next/font/google";

import Providers from "@/providers/providers";
import { Toaster } from "@/components/ui/sonner";

const beVietNamPro = Be_Vietnam_Pro({
  subsets: ["vietnamese"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-be-vietnam-pro",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ekofy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${beVietNamPro.variable} ${poppins.variable} bg-main-dark-bg font-bepro antialiased`}>
        <Providers>{children}</Providers>
        <Toaster
          theme="dark"
          richColors
          position="bottom-center"
          offset={{
            bottom: 60,
            right: 12,
          }}
          duration={3500}
        />
      </body>
    </html>
  );
}
